### PR TITLE
Add Google Cloud Storage integration

### PR DESCRIPTION
**Pull request by siboehm**
Via Google's [google-cloud-storage](https://googleapis.dev/python/storage/latest/index.html) library.
SimpleKV has support for google cloud storage through `boto`, however that doesn't work for Python3.

Testing is done using https://github.com/fsouza/fake-gcs-server.

### CODE REVIEW

**Review by fjetter — APPROVED** [review]
Nice, thank you! LGTM

**Comment by mlondschien** [comment]
Any possibility to get this into master and released? @mbr @fmarczin

**Review by fmarczin — APPROVED** [review]
Great addition. Thank you!

**Comment by xhochy** [comment]
Any chance to get this merged and released?

**Comment by mlondschien** [comment]
This three month old PR is approved by two different reviewers. https://github.com/JDASoftwareGroup/storefact/pull/19 depends on it. We have a dependence on both. Can we please get this merged and released? @fjetter @fmarczin @mbr.

**Comment by xhochy** [comment]
Well, let's fork it.

**Pull request merged**
