### PR TITLE
Ignore directory entries in FilesystemStore

### PR DESCRIPTION
**Pull request by fmarczin**
Currently, if the root of a FilesystemStore contains directories, the .keys()-method also returns those entries, which lead to errors in .put()/.get() etc.

This patch removes directory entries from .keys() and ._has_key()

### CODE REVIEW

**Comment by mbr** [comment]
What on earth are you putting inside your Filesystem Stores? =) I'll have to check this out and maybe write a few tests first. Thanks for pointing it out.

**Comment by fmarczin** [comment]
I added a test for the case that is handled differently (directory entries in storage). The tests pass on py27, the failures on py33 seem unrelated to this PR.

**Comment by mbr** [comment]
Thanks for the patch. I can merge this, but there's one thing I'm still unsure about: Is there a valid use case for not giving a storage exclusive access to a directory?

**Comment by fmarczin** [comment]
This change is more intended as something to make simplekv more robust and consistent when it encounters weird/invalid data. I can't come up with a proper use-case where this would happen on purpose 😄

**Comment by mbr** [comment]
The issue is that is comes at a significant cost -- a syscall for every
file inside the directory when listing keys.

Assuming you have a directory with 500,000 keys, `os.listdir` can still be
fast, but calling `stat` on each of them creates some unnecessary overhead.

**Comment by fmarczin** [comment]
Ah, that is true of course. I hadn't considered this before. 

I did some research, and sadly, the directory bit is actually available in the POSIX calls that happen during os.listdir(), but they aren't used. ("d_type: This field contains a value indicating the file type, making it possible to avoid the expense of calling lstat(2) if further actions depend on the type of the file.": http://man7.org/linux/man-pages/man3/readdir.3.html)
https://github.com/python/cpython/blob/f25c93de2cdef8d96a91fafbdcf77b9bb8d8492a/Modules/posixmodule.c#L3539

So, yeah. This adds a call to stat/lstat for each entry. I can completely understand why you wouldn't want to merge this. Close this if you want.

**Pull request closed without merging**
